package prosperpay.weather.api.weathersdk;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
@Disabled("SDK is not a Spring Boot app — disabling autogenerated test")
class WeatherSdkApplicationTests {

    @Test
    void contextLoads() {
    }

}
